Repository checkmarx-ltd/Bamboo-Plugin, pull requests merged in 2023-01, with the labels that each got.

#40 ForceScan Option included in BAMBOO plugin
  src/main/java/com/cx/plugin/configuration/AgentTaskConfigurator.java
  src/main/java/com/cx/plugin/utils/CxConfigHelper.java
  src/main/java/com/cx/plugin/utils/CxParam.java
  src/main/java/com/cx/plugin/utils/CxPluginUtils.java
  src/main/resources/com/cx/plugin/editExampleTask.ftl
  src/main/resources/english.properties
Labels: size/S

#39 Code changes for ability to enable/disable SAST scan.
  src/main/java/com/cx/plugin/configuration/AgentTaskConfigurator.java
  src/main/java/com/cx/plugin/utils/CxConfigHelper.java
  src/main/java/com/cx/plugin/utils/CxParam.java
  src/main/java/com/cx/plugin/utils/CxPluginUtils.java
  src/main/resources/com/cx/plugin/editExampleTask.ftl
  src/main/resources/english.properties
Labels: size/L

#41 Made UI changes for SCA Resolver
  src/main/resources/com/cx/plugin/cxGlobalConfig.ftl
  src/main/resources/com/cx/plugin/editExampleTask.ftl
  src/main/resources/english.properties
Labels: size/XS

#42 Added ui level changes for force scan checkbox.
  src/main/java/com/cx/plugin/utils/CxPluginUtils.java
  src/main/resources/com/cx/plugin/editExampleTask.ftl
Labels: size/XS

#43 Sca vulnerabilities fixes and handling of old plans for Enable SAST scan field.
  pom.xml
  src/main/java/com/cx/plugin/configuration/AgentTaskConfigurator.java
  src/main/java/com/cx/plugin/utils/CxConfigHelper.java
  src/main/resources/com/cx/plugin/editExampleTask.ftl
  src/main/resources/english.properties
Labels: size/M

#44 Made UI level changes for force scan description.
  src/main/resources/english.properties
Labels: size/XS
