Repository checkmarx-ltd/Bamboo-Plugin, pull requests merged in 2025-09, with the labels that each got.

#72 Merging Changes from Q3 Integration branch
  src/main/java/com/cx/plugin/task/CheckmarxTask.java
  src/main/java/com/cx/plugin/testConnection/CxRestResource.java
  src/main/java/com/cx/plugin/utils/CxParam.java
Labels: size/M

#73 URL modification for cxarmPolicyUrl
  src/main/java/com/cx/plugin/task/CheckmarxTask.java
Labels: size/S

#74 Bug fix for only sca scan
  pom.xml
  src/main/java/com/cx/plugin/task/CheckmarxTask.java
Labels: size/M

#76 Update version to 2025.4.4 and fixed bugs.
  pom.xml
  src/main/java/com/cx/plugin/conditions/DisplayResultsCondition.java
  src/main/java/com/cx/plugin/configuration/CxGlobalConfig.java
  src/main/java/com/cx/plugin/results/CxJobResultsWebPanel.java
  src/main/java/com/cx/plugin/results/CxPlanResultsWebPanel.java
  src/main/java/com/cx/plugin/task/CheckmarxTask.java
  src/main/resources/com/cx/plugin/editExampleTask.ftl
Labels: size/L

#77 Update version to 2025.4.5 and modify dependency exclusions and upgrade versions.
  pom.xml
Labels: size/L

#80 Update common.client.version to 2025.3.31 in pom.xml
  pom.xml
Labels: size/XS
